server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticketdesk_ticket?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Kishore@052816}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      properties:
        max.block.ms: 2000
        request.timeout.ms: 2000
        delivery.timeout.ms: 3000
        linger.ms: 0

logging:
  level:
    com.ticketdesk: DEBUG
